[package]
name = "graphis-node"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
graphis-core = { path = "../../core/" }
napi = { version = "3.7.0", features = ["napi4"] }
napi-derive = "3.4.0"
svg = "0.18.0"

[build-dependencies]
napi-build = "2.3.1"
